### PR TITLE
modify request description

### PR DESCRIPTION
**Pull request by keyganker**
the origin description is wrong, for GET method, only support query string params or json request body with header `Content-Type: application/json`

### CODE REVIEW

**Comment by keyganker** [comment]
@dexter-2 please have a review

**Comment by dexter-2** [comment]
@keyganker `/user/leverage/save` is POST endpoint, should be `/user/leverage`?

**Comment by dexter-2** [comment]
I am confused... In the section you added you make a GET request but to a POST endpoint, and the JSON request looks like you are changing leverage.

Is the example supposed to mean: all GET endpoint can use JSON?

**Comment by keyganker** [comment]
> @keyganker `/user/leverage/save` is POST endpoint, should be `/user/leverage`?

yes， should be  `/user/leverage`, I will fix it and use another endpoint which with query params

**Comment by keyganker** [comment]
> I am confused... In the section you added you make a GET request but to a POST endpoint, and the JSON request looks like you are changing leverage.
> 
> Is the example supposed to mean: all GET endpoint can use JSON?

Yes, all GET endpoint can use JSON with `application/json` header.
And  if we put query string in request body with `application/x-www-form-urlencoded` header,   the program can't parse it out at present, and we'll support it in the future.

**Comment by dexter-2** [comment]
> Yes, all GET endpoint can use JSON in request body with `application/json` header.
> And if we put query string in request body with `application/x-www-form-urlencoded` header, the program can't parse it out at present, and we'll support it in the future.

Gotcha. Everything looks fine but I have added capitalisation here: #68

**Pull request merged**
